### ISSUE TITLE
Unable to run jar file.

### ISSUE THREAD

**Issue by harjitsinghfk** [eBay/mtdtool#1]
harjit:ManualTestDemultiplexer harjit.singh$ java -jar MTD.jar 
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: com/google/common/base/Joiner
    at com.android.ddmlib.AndroidDebugBridge.startAdb(AndroidDebugBridge.java:960)
    at com.android.ddmlib.AndroidDebugBridge.start(AndroidDebugBridge.java:715)
    at com.android.ddmlib.AndroidDebugBridge.createBridge(AndroidDebugBridge.java:326)
    at com.ebay.testdemultiplexer.connection.TestDeviceManager.initializeADBConnection(TestDeviceManager.java:99)
    at com.ebay.testdemultiplexer.ManualTestDemultiplexer.main(ManualTestDemultiplexer.java:105)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Joiner
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 10 more
^C

can someone please help.

**Comment by byarger-ebay** [comment]
Hi Harjit,

It looks like a couple of the jar version numbers changed. Unfortunately, the version numbers were hardcoded in the build script. This is being modified to be more flexible with jar dependency versioning. Look for an update soon.

-Ben

**Comment by byarger-ebay** [comment]
Fix is in. Please pull.
